### ISSUE TITLE
FEATURE REQUEST (not an issue): Easy x0xheart integration with 8 note knobs and note display. Thanks in advance! 

### ISSUE THREAD

**Issue by 01GOD** [midilab/aciduino#1]
Hi, 

Would be great to make this easy to use with the x0xheart project as a full sequencer. Add a nice little blue note display and 8 step knobs for notes. 

Thanks in advance!

**Comment by 01GOD** [comment]
Oh I see. Here are some things found during research. (I don't have a
x0xheart handy yet)

Have a look at the "punkseq10" here. There is a build video.
https://www.whitefordresearch.com/products/punkseq10-preorder?variant=45657478407

Also look at this with a little display:
https://www.youtube.com/watch?v=emMyMncFpMk

Keeping it SIMPLE on the electronics build side is DEFINITELY recommended.
That is one thing that is really cool about this. Modding things in
software logic is much easier to handle later.

Adding a "7 segment display" or LCD (because OLED has ghosting issues) in
the center of that punkseq10 and adding slide and accent would be a nice
way forward.

Looking forward to trying an aciduino 2. Thanks in advance for making it an
awesome sequencer! Honestly the community really needs a proper DIY
sequencer for the x0xheart and MB33 Retro.

**Comment by midilab** [comment]
This little display on the video is a OLED one, the same i was told you, but with less pixel space(128x32 vs 128x68). I had manage to work with that display without ghosting issues(most of the times it happens because of the shared interface of SPI or I2C with another subsystem), it works really nice and has a good visibility for night and day.

As soon as i have time to, i will try to finish the PCB for the aciduino v2, some changes like swap the arduino nano for a ardunio pro micro to have a USB/MIDI connection that will help people integrate computer setup with standalone acid basses, or even virtual acid basses on PC will be an easier setup option.

This project is part of a bigger project(not released yet) for a complete full multitrack DIY sequencer using arduino mega(16 tracks, 4 midi in/out, usb/midi, sdcard support for pattern save/load, pattern matrix remix - like ableton scene mode - and other goodies for sequencer dudes out there), just like a midibox seqv4 one.

My bad i had miss a MB33 deal last year... :( hope to get myself a xOxheart soon!

**Comment by SeanTurner026** [comment]
> This project is part of a bigger project(not released yet) for a complete full multitrack DIY sequencer using arduino mega(16 tracks, 4 midi in/out, usb/midi, sdcard support for pattern save/load, pattern matrix remix - like ableton scene mode - and other goodies for sequencer dudes out there), just like a midibox seqv4 one.

Has this one come out yet? Otherwise, aciduino is a cool project! I've wanted to do something like this for a few years now

**Comment by doctea** [comment]
Chiming in too because this is also one I have been hopefully waiting for? :)

**Comment by midilab** [comment]
> > This project is part of a bigger project(not released yet) for a complete full multitrack DIY sequencer using arduino mega(16 tracks, 4 midi in/out, usb/midi, sdcard support for pattern save/load, pattern matrix remix - like ableton scene mode - and other goodies for sequencer dudes out there), just like a midibox seqv4 one.
> 
> Has this one come out yet? Otherwise, aciduino is a cool project! I've wanted to do something like this for a few years now

The 8 tacks sequencer is not released yet, but it is sitting here with me, my personal sequencer for loop music nowdays.

![jahtari-sequencer](https://user-images.githubusercontent.com/3717103/79144675-be07c200-7d95-11ea-8805-e5fd55a2a127.jpg)

**Comment by midilab** [comment]
> Chiming in too because this (that is, the 'aciduino v2 pcb') is also one I have been hopefully waiting for? :)

Im just trying to get some time to continue my work on it, but for sure it will be released this year...
For now some drafts i came up so far for the PCB thing, getting smaller and easier to make, by using a OLED screen we can minimize the interface for a clean design(the CV Converters goes on the middle of protoboard)
I had pickup the arudino pro micro because of his in-built capatibilities to act as a standalone midicontroller also for USB on computer side(avoid the use of serial to midi converters on the way). So that said, we can easily integrate our CV modular setup with computers for clock sync and other goodies.

![aciduino-v2-drafts](https://user-images.githubusercontent.com/3717103/79144829-01623080-7d96-11ea-9bde-ebcea56d0f01.jpg)

**Comment by midilab** [comment]
Finished the final layout of aciduino V2.

On the empty middle we can chose go for:

* CV/GATE 2 channels 12bits  
* MIDI Input  

Still working on CV/Gate module...

![aciduinov2-layout](https://user-images.githubusercontent.com/3717103/82732415-756fec80-9ce3-11ea-9d80-74cc585a298e.jpeg)

**Comment by 01GOD** [comment]
Saw now. Nice! Thanks!

If I can get a x0xheart for a decent price, likely make one of these soon.

**Comment by midilab** [comment]
First steps almost done.

Schematic is ready and the source code almost done.

The idea behind the minimal is to make it esiear to build but also to extend, here is where it goes the cv/gate request for modular that will be coded soon.

[https://github.com/midilab/aciduino/blob/aciduino_v2/AciduinoV2/aciduino_v2.png](aciduino v2 schematics)

**Comment by midilab** [comment]
closing this issue since the release of aciduino 2 is comming.

first steps is the basic module, then you can extend it for more detent encoders or pots as you wish
