### ISSUE TITLE
Generative "feature"

### ISSUE THREAD

**Issue by 2b2a2t2** [midilab/aciduino#18]
Hello, enjoying this V2.0.0Beta 4 so far... except this little feature or bug : 

if I use the generate button in one voice of one 808 engine, the generate settings are recorded so if I switch voice I still keep the last generate setting for this voice (I always inherit the previous fill, accent and roll setting if switch tho).

if I use the generate button in a 303 engine, the other 303 track only keeps the 1st setting page and the second page inherits from the previous track settings, so each time I change Track I lose all the fill, accent, slide, tie, tones, octave and octaves settings.

That being said, I like when switching to new 303 engine, the scale is kept from the previous and the length is reset to default

Would it be possible to increase the number of physical knobs like on V1 for a faster tweaking control ? I saw the code include encoders... Could I open a case for each question I have ? I don't want to pollute your project tho !

cheers

**Comment by midilab** [comment]
Hi @2b2a2t2 ,

No problem at all about open a case for each question/request, thats what a beta is for and im always ears to the end-user and those UI/UX interactions thoughts are really important at that beta stage.

Its quite doable to make those changes(generative parmeters per track), but i haven't done so far because of memory limitations of teensy LC im working with. So my plan is to create some options for the enduser before compiling to choose what features he want, so we can go from a minimun features(teensy lc with a lite aciduino version) but fully functional to a more featuread(teensy 3.2/3.6/4.0/4.1) version with maybe sampler capatibilities and keep it choices for builders to get a cheaper teensy and get a working version.

So for now you can leave this request opened, i will implement that as soon as i get the options feature avaliable, so you can compile using teensy 3.2.

uCtrl allows you to extends up to 64 pots if you wish, just a matter of connect some 4051 and initiate the driver on uCtrl accordly. Those extensions are also on the roadmap for a modular like aciduino(a brain like the lite version we have so far and a module with lots of pots too or a module for CV/Gating).

**Comment by midilab** [comment]
Implemented on [added generative per track parameters](https://github.com/midilab/aciduino/commit/638579dc2ba3932fe83113d9c2282152f62046cc)
