### ISSUE TITLE
Hardware ideas

### ISSUE THREAD

**Issue by 2b2a2t2** [midilab/aciduino#20]
to get some better feedback and fewer wires, could some lite neopixel  (or FASTLED) support be implemented to your library ?
Maybe this is stupid : switching for a SPI screen would free the I2C bus a bit and allow the use of MCP23017 so you can ideally link up to 8 of these and get 128 CV/triggers ?

**Comment by midilab** [comment]
everything related to input/output extension is handle by uCtrl DIN and DOUT driver modules, there you can use to driver 595/165 shiftregisters for buttons/encoders and leds.

SPI is going for CV module and other subsystems, since the subsystem is shared i got really bad response from those SPI oled screens.
