### ISSUE TITLE
Software installation tutorial

### ISSUE THREAD

**Issue by riegerben** [midilab/aciduino#32]
Hi,
I cant find out how to upload the code to the arduino nano.
Thanks :)

**Comment by midilab** [comment]
Hey @riegerben 

You just have to install Arduino IDE on you computer, after that, download the repository and open v1/Aciduino/Aciduino.ino.

You can find on the internet details about configure and upload the opened project to your arduino nano
https://support.arduino.cc/hc/en-us/articles/4733418441116-Upload-a-sketch-in-Arduino-IDE

I didn't write a installation tutorial because it will be a redundant work to write and maitain it updated since we already have the official Arduino community doing that.
