### ISSUE TITLE
V2 MidiExternalSync

### ISSUE THREAD

**Issue by canetisfluctus** [midilab/aciduino#39]
Hi, 

has anyone managed to get MIDI_STANDARD(0) working in version 2, so not USB_MIDI but MIDI for use with 5 pin connector? Or even better, has anyone manage to add a CV/Gate output code to Aciduino? I would appreciate any help! 

PS: I'm trying to get Aciduino working with a VCO. I have a Midi to CV module ready to convert the midi signals as well. 

Thanks in advance.

Best,

**Comment by midilab** [comment]
Yes, I'm using MIDI output, and by default, all platforms come configured with 1 Serial port for MIDI in/out.

For Teensys and ESP32, it will be Serial1.
For Arduino Mega, it will be Serial3.

You can search the internet for instructions on how to create and connect the circuit and the correct Serial pins depending on your arduino board. The output circuit is quite simple, typically requiring only three resistors. However, the input schematic is more complex as it involves an Optocoupler IC. Alternatively, you can find ready-to-use MIDI boards with Serial input/output online, which can be a cost-effective and convenient option.

Please keep in mind that the schematic will vary depending on the microcontroller you are using due to differences in working voltage.

For Arduino Mega, which operates at 5V, you can use this schematic: [https://github.com/midilab/uMODULAR/blob/master/lib/midi-io-5v.pdf](uModular 5v MIDI module)  

For Teensys and ESP32, which use a 3.3V serial connection, you will need to search online for a MIDI schematic compatible with these devices.

I have plans to add support for CV/Gate on the roadmap, but I currently lack any CV/Gate devices or modular equipment for testing. This is the primary reason I haven't implemented anything related to that yet.
